//
//  Problem029.m
//  Project Euler
//
//  Created by Matt Jones on 1/3/11.
//  Copyright 2011 Mr Mustard Media. All rights reserved.
//

#import "Problem029.h"


@implementation Problem29

- (id) init
{
	NSString *t = @"Problem 29";
	NSString *st = @"How many distinct terms are in the sequence generated by "
					"a^b for 2 <= a <= 100 and 2 <= b <= 100?";
	NSString *d = @"Consider all integer combinations of a^b for 2 <= a <= 5 "
	"and 2 <= b <= 5:\n"
	"\n\t2^2=4, 2^3=8, 2^4=16, 2^5=32"
	"\n\t3^2=9, 3^3=27, 3^4=81, 3^5=243"
	"\n\t4^2=16, 4^3=64, 4^4=256, 4^5=1024"
	"\n\t5^2=25, 5^3=125, 5^4=625, 5^5=3125\n\n"
	"If they are then placed in numerical order, with any repeats removed, we "
	"get the following sequence of 15 distinct terms:\n\n\t"
	"4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125\n\n"
	"How many distinct terms are in the sequence generated by a^b for 2 <= a "
	"<= 100 and 2 <= b <= 100?";
	self = [super initWithTitle:t subtitle:st description:d solved:YES];
	
	return self;
}

- (NSString *) solve:(ProblemViewController *)pvc
{
	[pvc performSelectorOnMainThread:@selector(addToConsole:) withObject:@"Initializing..." waitUntilDone:NO];
	int num = 99 * 99 + 1;
	
	[pvc performSelectorOnMainThread:@selector(addToConsole:) withObject:@"Calculating..." waitUntilDone:NO];
	for (int i=2; i<100; i++) 
	{
		for (int j=i*i; j<=100; j*=i) 
		{
			num = num - (int)(100 * (log(i) / log(j))) + 1;
		}
	}
	
	return [NSString stringWithFormat:@"%d", num];
}

@end
