//
//  Problem2.m
//  Project Euler
//
//  Created by Matt Jones on 12/7/10.
//  Copyright 2010 Mr Mustard Media. All rights reserved.
//

#import "Problem002.h"


@implementation Problem2

- (id) init
{
	NSString *t = @"Problem 2";
	NSString *st = @"Find the sum of all the even-valued terms in the "
					"Fibonacci sequence which do not exceed four million.";
	NSString *d = @"Each new term in the Fibonacci sequence is generated by "
				   "adding the previous two terms. By starting with 1 and 2, "
				   "the first 10 terms will be:\n\n\t1, 2, 3, 5, 8, 13, 21, "
				   "34, 55, 89, ...\n\nFind the sum of all the even-valued "
				   "terms in the sequence which do not exceed four million.";
	self = [super initWithTitle:t subtitle:st description:d solved:YES];
	
	return self;
}

- (NSString *) solve:(ProblemViewController *)pvc
{
	[pvc performSelectorOnMainThread:@selector(addToConsole:) withObject:@"Initializing..." waitUntilDone:NO];
	NSInteger sum = 0;
	NSInteger n1 = 1;
	NSInteger n2 = 2;
	
	[pvc performSelectorOnMainThread:@selector(addToConsole:) withObject:@"Calculating..." waitUntilDone:NO];
	while (n2 < 4000000) 
	{
		if (n2 % 2 == 0) 
		{
			sum += n2;
		}
		
		NSInteger next = n1 + n2;
		n1 = n2;
		n2 = next;
	}
	
	return [NSString stringWithFormat:@"%d", sum];
}

@end
